
create table if not exists public.matches (
  id bigint generated by default as identity primary key,
  team text not null check (team in ('U15','U16','U18','JWR')),
  match_date date not null,
  opponent text not null,
  competition text,
  home_away text,
  created_by text,
  created_at timestamptz not null default now()
);

create table if not exists public.goal_events (
  id bigint generated by default as identity primary key,
  match_id bigint not null references public.matches(id) on delete cascade,
  team text not null check (team in ('U15','U16','U18','JWR')),
  event_type text not null check (event_type in ('Tor','Gegentor')),
  minute integer,
  scorer text,
  assister text,
  phase text,
  creation_type text,
  start_x numeric, start_y numeric, start_zone text,
  assist_x numeric, assist_y numeric, assist_zone text,
  finish_x numeric, finish_y numeric, finish_zone text,
  video_url text,
  comment text,
  click_count integer not null default 3,
  finish_touch text,
  set_piece_type text,
  created_by text,
  created_at timestamptz not null default now()
);

create index if not exists idx_matches_team_date on public.matches(team, match_date desc);
create index if not exists idx_goal_events_team_match on public.goal_events(team, match_id);
