-- SV Ried AKA Goal Dashboard
-- Run this complete script once in Supabase -> SQL Editor.

create table if not exists public.matches (
  id bigint generated by default as identity primary key,
  team text not null check (team in ('U15','U16','U18','JWR','Profis')),
  match_date date not null,
  opponent text not null,
  competition text check (competition is null or competition in ('Testspiel','Punktspiel')),
  home_away text,
  created_by text,
  created_at timestamptz not null default now()
);

create table if not exists public.goal_events (
  id bigint generated by default as identity primary key,
  match_id bigint not null references public.matches(id) on delete cascade,
  team text not null check (team in ('U15','U16','U18','JWR','Profis')),
  event_type text not null check (event_type in ('Tor','Gegentor')),
  minute integer check (minute is null or minute between 0 and 130),
  scorer text,
  assister text,
  phase text,
  creation_type text,

  start_x double precision check (start_x is null or start_x between 0 and 100),
  start_y double precision check (start_y is null or start_y between 0 and 100),
  start_zone text,

  assist_x double precision check (assist_x is null or assist_x between 0 and 100),
  assist_y double precision check (assist_y is null or assist_y between 0 and 100),
  assist_zone text,

  finish_x double precision check (finish_x is null or finish_x between 0 and 100),
  finish_y double precision check (finish_y is null or finish_y between 0 and 100),
  finish_zone text,

  video_url text,
  comment text,

  click_count integer not null default 3 check (click_count between 1 and 3),
  finish_touch text check (
    finish_touch is null or finish_touch in ('One Touch','Two Touch','>2 Touches')
  ),
  set_piece_type text check (
    set_piece_type is null or set_piece_type in ('Eckball links','Eckball rechts','Elfmeter')
  ),

  created_by text,
  created_at timestamptz not null default now()
);

create index if not exists idx_matches_team_date
  on public.matches(team, match_date desc);

create index if not exists idx_goal_events_team_match
  on public.goal_events(team, match_id);

create index if not exists idx_goal_events_event_type
  on public.goal_events(event_type);

create index if not exists idx_goal_events_created_at
  on public.goal_events(created_at);

-- The Streamlit app uses a server-side Supabase secret/service-role key.
-- RLS can therefore remain enabled without public policies.
alter table public.matches enable row level security;
alter table public.goal_events enable row level security;
